dist: xenial
sudo: false
language: python
cache: pip
python:
  - 3.7
services:
  - postgresql
# Matrix composition:
# Django LTS versions: All supported Python releases
# Other versions and master branch: The newest possible Python release
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
    - python: 3.7
      env: REQ="Django>=3.0b1,<3.1"
    - python: 3.6
      env: REQ="Django>=3.0b1,<3.1"
    - python: 3.7
      env: REQ="Django>=2.2,<3.0"
    - python: 3.6
      env: REQ="Django>=2.2,<3.0"
    - python: 3.5
      env: REQ="Django>=2.2,<3.0"
    - python: 3.7
      env: REQ="Django>=2.1,<2.2"
    - python: 3.7
      env: REQ="Django>=2.0,<2.1"
    - python: 3.7
      env: REQ="Django>=1.11,<2.0"
    - python: 3.6
      env: REQ="Django>=1.11,<2.0"
    - python: 3.5
      env: REQ="Django>=1.11,<2.0"
    - python: 3.7
      env: REQ="black flake8"
      install:
        - pip install black flake8
      script:
        - flake8 .
        - black --check feincms3 tests
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
install:
- pip install -U pip setuptools wheel
- pip install $REQ
- pip install django-ckeditor django-content-editor django-imagefield
- pip install django-tree-queries html-sanitizer psycopg2-binary requests
- python setup.py install
script: cd tests && ./manage.py test -v 2 testapp && cd ..
