language: python
cache: pip
sudo: false
python:
- "3.6"
- "3.5"
- "2.7"
addons:
  postgresql: "9.4"
env:
- REQ="Django>=1.11,<2.0"
- REQ="Django>=2.0,<2.1"
- REQ="Django>=2.1,<2.2
- REQ="https://github.com/django/django/archive/master.zip#egg=Django"
matrix:
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
  exclude:
    - python: "2.7"
      env: REQ="Django>=2.0,<2.1"
    - python: "2.7"
      env: REQ="Django>=2.1,<2.2"
    - python: "2.7"
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
install:
- pip install -U pip setuptools wheel
- pip install $REQ
- pip install django-ckeditor django-content-editor django-imagefield
- pip install django-tree-queries html-sanitizer psycopg2-binary requests
- python setup.py install
script: cd tests && ./manage.py test -v 2 testapp && cd ..

jobs:
  include:
    - stage: style
      env: REQ=none
      install: skip
      script:
        - pip install black flake8
        - flake8 .
        - black --check feincms3 tests
